version: '3'

services:
  frontend:
    build: frontend
    ports:
    - "8000:80"
    image: docker.pkg.github.com/jakmar17/exchangeapp-diploma/exchangeapp-frontend:0.0.1

  restapi:
    build: backend/rest-api
    ports:
    - "8001:80"
    image: docker.pkg.github.com/jakmar17/exchangeapp-diploma/exchangeapp-restapi:0.0.1

  static-sites:
    build: backend/static-sites
    ports:
    - "8002:80"
    image: docker.pkg.github.com/jakmar17/exchangeapp-diploma/exchangeapp-staticsites:0.0.1

  email:
    build: backend/email-server
    image: docker.pkg.github.com/jakmar17/exchangeapp-diploma/exchangeapp-email:0.0.1

#  db:
#    image: mariadb
#    volumes:
#      - ./database-data:/var/lib/mysql
#      - ./database-init-files:/docker-entrypoint-initdb.d
#    restart: on-failure
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: MarelaGoriva