# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PERSONAL_ACCESS_CODE: ${{ secrets.PERSONAL_ACCESS_CODE }}
        run: |
          # docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker login docker.pkg.github.com -u jakmar17 -p $PERSONAL_ACCESS_CODE
      - name: docker backend build
        run: |
          docker build ./backend -t docker.pkg.github.com/jakmar17/exchangeapp-diploma/exchangeapp-backend:0.0.1
          # jakmar17/exchangeapp-backend:0.0.1
      - name: docker push
        run: |
          docker push docker.pkg.github.com/jakmar17/exchangeapp-diploma/exchangeapp-backend:0.0.1
          
          # docker push jakmar17/exchangeapp-backend:0.0.1
